#!/bin/python3

import math
import os
import random
import re
import sys



def solve(s):
    words = s.split(' ')   # split by space to preserve multiple spaces
    result = []

    for word in words:
        if word:
            result.append(word[0].upper() + word[1:])
        else:
            result.append(word)

    return ' '.join(result)


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
