#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    s = input()
from collections import Counter

counts = Counter(s)
for ch, cnt in sorted(counts.items(), key=lambda x: (-x[1], x[0]))[:3]:
    print(ch, cnt)
